# These are supported funding model platforms

github: ptprashanttripathi
patreon: ptprashanttripathi
open_collective: ptprashanttripathi
ko_fi: ptprashanttripathi
tidelift: npm/ptprashanttripathi
community_bridge: ptprashanttripathi
liberapay: ptprashanttripathi
issuehunt: ptprashanttripathi
otechie: ptprashanttripathi
custom: ["https://paypal.me/ptprashanttripathi"]
